### ISSUE TITLE
Showing a summary only?

### ISSUE THREAD

**Issue by RandomlyKnighted** [DavidAnson/grunt-check-pages#4]
When running jscs the output I get looks like this:

```
Running "jscs:src" (jscs) task
>> 3 files without code style errors.
```

Is there a way to get a similar summary output without actually displaying each of the links that is checked?

**Comment by RandomlyKnighted** [comment]
@DavidAnson just wanted to follow up on this and see if you've had a chance to look into it?

**Comment by DavidAnson** [comment]
This is at the front of my queue. (Something jumped in front last week, but is done now.)

**Comment by RandomlyKnighted** [comment]
I almost forgot to mention that the 

`summary: true`

flag is a bit misleading. I've got that flag set in my grunt file but originally when I saw that my expectation is that it would display info like I mentioned above. Whenever this feature is added it'd probably make more sense to the user if it was named summary and the detailed summary that is provided by the flag above had a different name.

**Comment by DavidAnson** [comment]
I'm reluctant to change the meaning of an existing option. What I've come up with instead is a new `terse` option that should do what you want. Here's what it looks like in `check-pages` (the underlying package): https://github.com/DavidAnson/check-pages/commit/0ef3b89d388c3162b81779e1e1ad2240ce662bdd

**Comment by RandomlyKnighted** [comment]
That's understandable. I just wanted to point out that it may cause some confusion.

`terse`? is that short for something or does it stand for something? I'm trying to think of a way to remember that option but nothing is coming to mind at the moment. Also was this included today's 0.10.0 release? If so, when can I expect this repo to be updated to use that version?

**Comment by DavidAnson** [comment]
`terse` is a short word that means something like "without using a lot of words". :) It's part of `check-pages` 0.10.0 specifically so I can include it in the next `grunt-check-pages` update. I should be able to release that in the next couple of days. Thanks for your patience!

**Comment by RandomlyKnighted** [comment]
No problem, and thank you for adding this feature!
